import Navbar from '@/components/Navbar';
import './globals.css';
import '@fontsource/inter'; // Import the Inter font from the package

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans">
        <Navbar />
        <main>{children}</main>
        </body>
    </html>
  );
}
